# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.admin_leaderboard import AdminLeaderboard
from ...types.create_leaderboards_request import CreateLeaderboardsRequest
from ...types.create_leaderboards_response import CreateLeaderboardsResponse
from ...types.delete_leaderboards_response import DeleteLeaderboardsResponse
from ...types.list_leaderboards_response import ListLeaderboardsResponse
from ...types.update_leaderboards_request import UpdateLeaderboardsRequest
from ...types.update_leaderboards_response import UpdateLeaderboardsResponse
from .raw_client import AsyncRawLeaderboardsClient, RawLeaderboardsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class LeaderboardsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLeaderboardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLeaderboardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLeaderboardsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListLeaderboardsResponse:
        """
        List leaderboards.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of records to return.

        skip : typing.Optional[int]
            Number of records to skip from the start of the list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListLeaderboardsResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.leaderboards.list(
            limit=1,
            skip=1,
        )
        """
        _response = self._raw_client.list(limit=limit, skip=skip, request_options=request_options)
        return _response.data

    def create(
        self, *, request: CreateLeaderboardsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateLeaderboardsResponse:
        """
        Create leaderboards. Maximum 100 leaderboards per request.

        Parameters
        ----------
        request : CreateLeaderboardsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateLeaderboardsResponse
            Successful operation (no leaderboards created)

        Examples
        --------
        from trophy import CreateLeaderboardRequestItem, TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.leaderboards.create(
            request=[
                CreateLeaderboardRequestItem(
                    name="Revenue Champions",
                    key="revenue-champions",
                    status="inactive",
                    rank_by="metric",
                    metric_id="550e8400-e29b-41d4-a716-446655440000",
                    max_participants=100,
                    start="2026-04-20",
                    breakdown_attributes=["550e8400-e29b-41d4-a716-446655440010"],
                    run_unit="month",
                    run_interval=1,
                ),
                CreateLeaderboardRequestItem(
                    name="Streak Legends",
                    key="streak-legends",
                    status="scheduled",
                    rank_by="streak",
                    start="2026-04-27",
                ),
            ],
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    def delete(
        self,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteLeaderboardsResponse:
        """
        Delete leaderboards by ID.

        Parameters
        ----------
        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Leaderboard IDs to delete. Repeat the query param or provide a comma-separated list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteLeaderboardsResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.leaderboards.delete()
        """
        _response = self._raw_client.delete(ids=ids, request_options=request_options)
        return _response.data

    def update(
        self, *, request: UpdateLeaderboardsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateLeaderboardsResponse:
        """
        Update leaderboards by ID. Updating `status` behaves the same as activating, scheduling, deactivating, or finishing a leaderboard in the dashboard.

        Parameters
        ----------
        request : UpdateLeaderboardsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateLeaderboardsResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi, UpdateLeaderboardRequestItem

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.leaderboards.update(
            request=[
                UpdateLeaderboardRequestItem(
                    id="550e8400-e29b-41d4-a716-446655440100",
                    name="Monthly Revenue Champions",
                    description="Ranked by monthly revenue",
                    status="active",
                ),
                UpdateLeaderboardRequestItem(
                    id="550e8400-e29b-41d4-a716-446655440101",
                    status="finished",
                ),
            ],
        )
        """
        _response = self._raw_client.update(request=request, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AdminLeaderboard:
        """
        Get a leaderboard by ID.

        Parameters
        ----------
        id : str
            The UUID of the leaderboard to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminLeaderboard
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.leaderboards.get(
            id="550e8400-e29b-41d4-a716-446655440100",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data


class AsyncLeaderboardsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLeaderboardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLeaderboardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLeaderboardsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListLeaderboardsResponse:
        """
        List leaderboards.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of records to return.

        skip : typing.Optional[int]
            Number of records to skip from the start of the list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListLeaderboardsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.leaderboards.list(
                limit=1,
                skip=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(limit=limit, skip=skip, request_options=request_options)
        return _response.data

    async def create(
        self, *, request: CreateLeaderboardsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateLeaderboardsResponse:
        """
        Create leaderboards. Maximum 100 leaderboards per request.

        Parameters
        ----------
        request : CreateLeaderboardsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateLeaderboardsResponse
            Successful operation (no leaderboards created)

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, CreateLeaderboardRequestItem

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.leaderboards.create(
                request=[
                    CreateLeaderboardRequestItem(
                        name="Revenue Champions",
                        key="revenue-champions",
                        status="inactive",
                        rank_by="metric",
                        metric_id="550e8400-e29b-41d4-a716-446655440000",
                        max_participants=100,
                        start="2026-04-20",
                        breakdown_attributes=["550e8400-e29b-41d4-a716-446655440010"],
                        run_unit="month",
                        run_interval=1,
                    ),
                    CreateLeaderboardRequestItem(
                        name="Streak Legends",
                        key="streak-legends",
                        status="scheduled",
                        rank_by="streak",
                        start="2026-04-27",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    async def delete(
        self,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteLeaderboardsResponse:
        """
        Delete leaderboards by ID.

        Parameters
        ----------
        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Leaderboard IDs to delete. Repeat the query param or provide a comma-separated list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteLeaderboardsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.leaderboards.delete()


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(ids=ids, request_options=request_options)
        return _response.data

    async def update(
        self, *, request: UpdateLeaderboardsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateLeaderboardsResponse:
        """
        Update leaderboards by ID. Updating `status` behaves the same as activating, scheduling, deactivating, or finishing a leaderboard in the dashboard.

        Parameters
        ----------
        request : UpdateLeaderboardsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateLeaderboardsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, UpdateLeaderboardRequestItem

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.leaderboards.update(
                request=[
                    UpdateLeaderboardRequestItem(
                        id="550e8400-e29b-41d4-a716-446655440100",
                        name="Monthly Revenue Champions",
                        description="Ranked by monthly revenue",
                        status="active",
                    ),
                    UpdateLeaderboardRequestItem(
                        id="550e8400-e29b-41d4-a716-446655440101",
                        status="finished",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(request=request, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AdminLeaderboard:
        """
        Get a leaderboard by ID.

        Parameters
        ----------
        id : str
            The UUID of the leaderboard to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminLeaderboard
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.leaderboards.get(
                id="550e8400-e29b-41d4-a716-446655440100",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data
