# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.points_boost import PointsBoost
from ..types.points_summary_response import PointsSummaryResponse
from ..types.points_system_response import PointsSystemResponse
from .raw_client import AsyncRawPointsClient, RawPointsClient


class PointsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPointsClient
        """
        return self._raw_client

    def summary(
        self,
        key: str,
        *,
        user_attributes: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PointsSummaryResponse:
        """
        Get a breakdown of the number of users with points in each range.

        Parameters
        ----------
        key : str
            Key of the points system.

        user_attributes : typing.Optional[str]
            Optional colon-delimited user attribute filters in the format attribute:value,attribute:value. Only users matching ALL specified attributes will be included in the points breakdown.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PointsSummaryResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.points.summary(
            key="points-system-key",
            user_attributes="plan-type:premium,region:us-east",
        )
        """
        _response = self._raw_client.summary(key, user_attributes=user_attributes, request_options=request_options)
        return _response.data

    def system(self, key: str, *, request_options: typing.Optional[RequestOptions] = None) -> PointsSystemResponse:
        """
        Get a points system with its triggers.

        Parameters
        ----------
        key : str
            Key of the points system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PointsSystemResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.points.system(
            key="points-system-key",
        )
        """
        _response = self._raw_client.system(key, request_options=request_options)
        return _response.data

    def boosts(
        self,
        key: str,
        *,
        include_finished: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[PointsBoost]:
        """
        Get all global boosts for a points system. Finished boosts are excluded by default.

        Parameters
        ----------
        key : str
            Key of the points system.

        include_finished : typing.Optional[bool]
            When set to 'true', boosts that have finished (past their end date) will be included in the response. By default, finished boosts are excluded.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PointsBoost]
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.points.boosts(
            key="points-system-key",
            include_finished=True,
        )
        """
        _response = self._raw_client.boosts(key, include_finished=include_finished, request_options=request_options)
        return _response.data


class AsyncPointsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPointsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPointsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPointsClient
        """
        return self._raw_client

    async def summary(
        self,
        key: str,
        *,
        user_attributes: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PointsSummaryResponse:
        """
        Get a breakdown of the number of users with points in each range.

        Parameters
        ----------
        key : str
            Key of the points system.

        user_attributes : typing.Optional[str]
            Optional colon-delimited user attribute filters in the format attribute:value,attribute:value. Only users matching ALL specified attributes will be included in the points breakdown.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PointsSummaryResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.points.summary(
                key="points-system-key",
                user_attributes="plan-type:premium,region:us-east",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.summary(
            key, user_attributes=user_attributes, request_options=request_options
        )
        return _response.data

    async def system(
        self, key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PointsSystemResponse:
        """
        Get a points system with its triggers.

        Parameters
        ----------
        key : str
            Key of the points system.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PointsSystemResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.points.system(
                key="points-system-key",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.system(key, request_options=request_options)
        return _response.data

    async def boosts(
        self,
        key: str,
        *,
        include_finished: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[PointsBoost]:
        """
        Get all global boosts for a points system. Finished boosts are excluded by default.

        Parameters
        ----------
        key : str
            Key of the points system.

        include_finished : typing.Optional[bool]
            When set to 'true', boosts that have finished (past their end date) will be included in the response. By default, finished boosts are excluded.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[PointsBoost]
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.points.boosts(
                key="points-system-key",
                include_finished=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.boosts(
            key, include_finished=include_finished, request_options=request_options
        )
        return _response.data
