# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .streak_frequency import StreakFrequency
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class StreakResponse(UniversalBaseModel):
    length: int = pydantic.Field()
    """
    The length of the user's current streak.
    """

    frequency: StreakFrequency = pydantic.Field()
    """
    The frequency of the streak.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
