# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.admin_points_boost import AdminPointsBoost
from ....types.create_points_boosts_request import CreatePointsBoostsRequest
from ....types.create_points_boosts_response import CreatePointsBoostsResponse
from ....types.delete_points_boosts_response import DeletePointsBoostsResponse
from ....types.list_points_boosts_response import ListPointsBoostsResponse
from ....types.patch_points_boosts_request import PatchPointsBoostsRequest
from ....types.patch_points_boosts_response import PatchPointsBoostsResponse
from .raw_client import AsyncRawBoostsClient, RawBoostsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BoostsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBoostsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBoostsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBoostsClient
        """
        return self._raw_client

    def list(
        self,
        system_id: str,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPointsBoostsResponse:
        """
        List points boosts for a system.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        limit : typing.Optional[int]
            Maximum number of results to return (1-100, default 10).

        skip : typing.Optional[int]
            Number of results to skip for pagination (default 0).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPointsBoostsResponse
            A paginated list of points boosts.

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.points.boosts.list(
            system_id="550e8400-e29b-41d4-a716-446655440000",
            limit=1,
            skip=1,
        )
        """
        _response = self._raw_client.list(system_id, limit=limit, skip=skip, request_options=request_options)
        return _response.data

    def create(
        self,
        system_id: str,
        *,
        request: CreatePointsBoostsRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePointsBoostsResponse:
        """
        Create points boosts.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        request : CreatePointsBoostsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePointsBoostsResponse
            Successful operation (no boosts created)

        Examples
        --------
        from trophy import CreatePointsBoostRequestItem, TrophyApi

        client = TrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.points.boosts.create(
            system_id="550e8400-e29b-41d4-a716-446655440000",
            request=[
                CreatePointsBoostRequestItem(
                    user_id="user-123",
                    name="Double XP Weekend",
                    start="2024-01-01",
                    end="2024-01-03",
                    multiplier=2.0,
                )
            ],
        )
        """
        _response = self._raw_client.create(system_id, request=request, request_options=request_options)
        return _response.data

    def delete(
        self,
        system_id: str,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePointsBoostsResponse:
        """
        Delete multiple points boosts by ID.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A list of up to 100 boost IDs.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePointsBoostsResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.points.boosts.delete(
            system_id="550e8400-e29b-41d4-a716-446655440000",
            ids=["ids"],
        )
        """
        _response = self._raw_client.delete(system_id, ids=ids, request_options=request_options)
        return _response.data

    def update(
        self,
        system_id: str,
        *,
        request: PatchPointsBoostsRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatchPointsBoostsResponse:
        """
        Update multiple points boosts.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        request : PatchPointsBoostsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatchPointsBoostsResponse
            Successful operation

        Examples
        --------
        from trophy import PatchPointsBoostsRequestItem, TrophyApi

        client = TrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.points.boosts.update(
            system_id="550e8400-e29b-41d4-a716-446655440000",
            request=[
                PatchPointsBoostsRequestItem(
                    id="550e8400-e29b-41d4-a716-446655440000",
                    name="Updated Boost Name",
                    multiplier=3.0,
                )
            ],
        )
        """
        _response = self._raw_client.update(system_id, request=request, request_options=request_options)
        return _response.data

    def get(
        self, system_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AdminPointsBoost:
        """
        Get a single points boost by ID.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        id : str
            The UUID of the points boost.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminPointsBoost
            The points boost.

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.points.boosts.get(
            system_id="550e8400-e29b-41d4-a716-446655440000",
            id="660f9500-f30c-42e5-b827-557766550001",
        )
        """
        _response = self._raw_client.get(system_id, id, request_options=request_options)
        return _response.data


class AsyncBoostsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBoostsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBoostsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBoostsClient
        """
        return self._raw_client

    async def list(
        self,
        system_id: str,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPointsBoostsResponse:
        """
        List points boosts for a system.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        limit : typing.Optional[int]
            Maximum number of results to return (1-100, default 10).

        skip : typing.Optional[int]
            Number of results to skip for pagination (default 0).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPointsBoostsResponse
            A paginated list of points boosts.

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.points.boosts.list(
                system_id="550e8400-e29b-41d4-a716-446655440000",
                limit=1,
                skip=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(system_id, limit=limit, skip=skip, request_options=request_options)
        return _response.data

    async def create(
        self,
        system_id: str,
        *,
        request: CreatePointsBoostsRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePointsBoostsResponse:
        """
        Create points boosts.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        request : CreatePointsBoostsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePointsBoostsResponse
            Successful operation (no boosts created)

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, CreatePointsBoostRequestItem

        client = AsyncTrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.points.boosts.create(
                system_id="550e8400-e29b-41d4-a716-446655440000",
                request=[
                    CreatePointsBoostRequestItem(
                        user_id="user-123",
                        name="Double XP Weekend",
                        start="2024-01-01",
                        end="2024-01-03",
                        multiplier=2.0,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(system_id, request=request, request_options=request_options)
        return _response.data

    async def delete(
        self,
        system_id: str,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeletePointsBoostsResponse:
        """
        Delete multiple points boosts by ID.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            A list of up to 100 boost IDs.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeletePointsBoostsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.points.boosts.delete(
                system_id="550e8400-e29b-41d4-a716-446655440000",
                ids=["ids"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(system_id, ids=ids, request_options=request_options)
        return _response.data

    async def update(
        self,
        system_id: str,
        *,
        request: PatchPointsBoostsRequest,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PatchPointsBoostsResponse:
        """
        Update multiple points boosts.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        request : PatchPointsBoostsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PatchPointsBoostsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, PatchPointsBoostsRequestItem

        client = AsyncTrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.points.boosts.update(
                system_id="550e8400-e29b-41d4-a716-446655440000",
                request=[
                    PatchPointsBoostsRequestItem(
                        id="550e8400-e29b-41d4-a716-446655440000",
                        name="Updated Boost Name",
                        multiplier=3.0,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(system_id, request=request, request_options=request_options)
        return _response.data

    async def get(
        self, system_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AdminPointsBoost:
        """
        Get a single points boost by ID.

        Parameters
        ----------
        system_id : str
            The UUID of the points system.

        id : str
            The UUID of the points boost.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminPointsBoost
            The points boost.

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            "1.15.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.points.boosts.get(
                system_id="550e8400-e29b-41d4-a716-446655440000",
                id="660f9500-f30c-42e5-b827-557766550001",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(system_id, id, request_options=request_options)
        return _response.data
