# This file was auto-generated by Fern from our API Definition.

from .achievement_response import AchievementResponse
import typing
import pydantic
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class AchievementWithStatsResponse(AchievementResponse):
    completions: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of users who have completed this achievement.
    """

    completed_percentage: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="completedPercentage")
    ] = pydantic.Field(default=None)
    """
    The percentage of all users who have completed this achievement.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
