# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .admin_points_level_badge import AdminPointsLevelBadge


class AdminPointsLevel(UniversalBaseModel):
    """
    A points level as returned from admin endpoints.
    """

    id: str = pydantic.Field()
    """
    The UUID of the level.
    """

    name: str = pydantic.Field()
    """
    The name of the level.
    """

    key: str = pydantic.Field()
    """
    The level key.
    """

    points: int = pydantic.Field()
    """
    The threshold points value for the level.
    """

    description: str = pydantic.Field()
    """
    The level description.
    """

    badge: typing.Optional[AdminPointsLevelBadge] = pydantic.Field(default=None)
    """
    The badge for the level, or null if no badge is set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
