# This file was auto-generated by Fern from our API Definition.

import typing

AdminAchievementTrigger = typing.Union[
    typing.Literal["metric", "streak", "api", "achievement", "anniversary"], typing.Any
]
