# This file was auto-generated by Fern from our API Definition.

import typing

AdminFontFamily = typing.Union[
    typing.Literal[
        "MODERN_SANS",
        "BOOK_SANS",
        "ORGANIC_SANS",
        "GEOMETRIC_SANS",
        "HEAVY_SANS",
        "ROUNDED_SANS",
        "MODERN_SERIF",
        "BOOK_SERIF",
        "MONOSPACE",
    ],
    typing.Any,
]
