# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .admin_achievement_badge import AdminAchievementBadge
from .admin_achievement_event_attributes_item import AdminAchievementEventAttributesItem
from .admin_achievement_status import AdminAchievementStatus
from .admin_achievement_trigger import AdminAchievementTrigger
from .admin_achievement_user_attributes_item import AdminAchievementUserAttributesItem


class AdminAchievement(UniversalBaseModel):
    """
    An achievement as returned from admin endpoints. Trigger-specific fields are only present for the matching trigger type.
    """

    id: str = pydantic.Field()
    """
    The UUID of the achievement.
    """

    name: str = pydantic.Field()
    """
    The achievement name.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A short description of the achievement.
    """

    trigger: AdminAchievementTrigger = pydantic.Field()
    """
    The achievement trigger type.
    """

    status: AdminAchievementStatus = pydantic.Field()
    """
    The achievement status.
    """

    badge: typing.Optional[AdminAchievementBadge] = pydantic.Field(default=None)
    """
    The badge for the achievement, or null if no badge is set.
    """

    user_attributes: typing_extensions.Annotated[
        typing.List[AdminAchievementUserAttributesItem],
        FieldMetadata(alias="userAttributes"),
        pydantic.Field(alias="userAttributes", description="User attribute filters applied to the achievement."),
    ]
    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    The achievement key. Only present for API achievements.
    """

    metric_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="metricId"),
        pydantic.Field(alias="metricId", description="The UUID of the metric. Only present for metric achievements."),
    ] = None
    metric_value: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="metricValue"),
        pydantic.Field(alias="metricValue", description="The metric threshold. Only present for metric achievements."),
    ] = None
    event_attributes: typing_extensions.Annotated[
        typing.Optional[typing.List[AdminAchievementEventAttributesItem]],
        FieldMetadata(alias="eventAttributes"),
        pydantic.Field(
            alias="eventAttributes", description="Event attribute filters. Only present for metric achievements."
        ),
    ] = None
    streak_length: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="streakLength"),
        pydantic.Field(alias="streakLength", description="The streak length. Only present for streak achievements."),
    ] = None
    anniversary_years: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="anniversaryYears"),
        pydantic.Field(
            alias="anniversaryYears", description="The anniversary years. Only present for anniversary achievements."
        ),
    ] = None
    achievement_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="achievementIds"),
        pydantic.Field(
            alias="achievementIds",
            description="Prerequisite achievement UUIDs. Only present for achievement achievements.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
