# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .admin_font_family import AdminFontFamily
from .admin_settings_branding_app_icon import AdminSettingsBrandingAppIcon
from .admin_settings_branding_logo import AdminSettingsBrandingLogo


class AdminSettingsBranding(UniversalBaseModel):
    """
    Organization branding settings.
    """

    app_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="appName"),
        pydantic.Field(alias="appName", description="The name of the app or platform."),
    ]
    app_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="appUrl"),
        pydantic.Field(alias="appUrl", description="The URL of the app or platform."),
    ]
    brand_color: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="brandColor"),
        pydantic.Field(
            alias="brandColor",
            description="Primary brand color as hex (`#RGB` or `#RRGGBB`), `rgb(r,g,b)`, or `rgba(r,g,b,a)`.",
        ),
    ]
    font: AdminFontFamily
    logo: typing.Optional[AdminSettingsBrandingLogo] = pydantic.Field(default=None)
    """
    Company logo used in emails, or `null` if none is set.
    """

    app_icon: typing_extensions.Annotated[
        typing.Optional[AdminSettingsBrandingAppIcon],
        FieldMetadata(alias="appIcon"),
        pydantic.Field(
            alias="appIcon", description="App icon used in push notification previews, or `null` if none is set."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
