# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .admin_tenant_status import AdminTenantStatus


class AdminTenant(UniversalBaseModel):
    """
    A tenant in a multi-tenant environment.
    """

    id: str = pydantic.Field()
    """
    The tenant UUID.
    """

    customer_id: typing_extensions.Annotated[str, FieldMetadata(alias="customerId")] = pydantic.Field()
    """
    The external customer ID for this tenant.
    """

    name: str = pydantic.Field()
    """
    Human-readable name for the tenant.
    """

    status: AdminTenantStatus = pydantic.Field()
    """
    The lifecycle status of the tenant.
    """

    created: dt.datetime = pydantic.Field()
    """
    When the tenant was created.
    """

    updated: dt.datetime = pydantic.Field()
    """
    When the tenant was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
