# This file was auto-generated by Fern from our API Definition.

import typing

from .bulk_streak_response_item import BulkStreakResponseItem

BulkStreakResponse = typing.List[BulkStreakResponseItem]
