# This file was auto-generated by Fern from our API Definition.

import typing

from .create_points_level_request_item import CreatePointsLevelRequestItem

CreatePointsLevelsRequest = typing.List[CreatePointsLevelRequestItem]
