# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CreatedApplicationKey(UniversalBaseModel):
    """
    A newly created application API key.
    """

    id: str = pydantic.Field()
    """
    The unique identifier of the API key. Use this ID to delete the key.
    """

    user_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="userId"),
        pydantic.Field(alias="userId", description="The user ID the key is scoped to."),
    ]
    key: str = pydantic.Field()
    """
    The full API key value. This is only returned once at creation time and cannot be retrieved again.
    """

    prefix: str = pydantic.Field()
    """
    The key prefix used for cache lookup.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
