# This file was auto-generated by Fern from our API Definition.

import typing

from .create_points_boost_request_item import CreatePointsBoostRequestItem

CreatePointsBoostsRequest = typing.List[CreatePointsBoostRequestItem]
