# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_insert_issue import BulkInsertIssue


class CreateStreakFreezesResponse(UniversalBaseModel):
    """
    Response containing any issues encountered while creating streak freezes.
    """

    issues: typing.List[BulkInsertIssue] = pydantic.Field()
    """
    Array of issues encountered during freeze creation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
