# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .create_leaderboard_request_item_rank_by import CreateLeaderboardRequestItemRankBy
from .create_leaderboard_request_item_run_unit import CreateLeaderboardRequestItemRunUnit
from .create_leaderboard_request_item_status import CreateLeaderboardRequestItemStatus


class CreateLeaderboardRequestItem(UniversalBaseModel):
    """
    A leaderboard to create.
    """

    name: str = pydantic.Field()
    """
    The leaderboard name.
    """

    key: str = pydantic.Field()
    """
    The leaderboard key. Only alphanumeric characters, hyphens, and underscores are permitted.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The leaderboard description.
    """

    status: typing.Optional[CreateLeaderboardRequestItemStatus] = pydantic.Field(default=None)
    """
    The initial user-facing status. Defaults to `inactive`. Use `scheduled` for leaderboards that should be active in the future and `finished` only when creating a leaderboard with an end date in the past.
    """

    rank_by: typing_extensions.Annotated[CreateLeaderboardRequestItemRankBy, FieldMetadata(alias="rankBy")] = (
        pydantic.Field()
    )
    """
    What the leaderboard ranks by.
    """

    metric_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="metricId")] = pydantic.Field(
        default=None
    )
    """
    The metric ID to rank by when `rankBy` is `metric`.
    """

    points_system_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="pointsSystemId")] = (
        pydantic.Field(default=None)
    )
    """
    The points system ID to rank by when `rankBy` is `points`.
    """

    max_participants: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="maxParticipants")] = (
        pydantic.Field(default=None)
    )
    """
    The maximum number of participants. Defaults to `1000`.
    """

    start: typing.Optional[str] = pydantic.Field(default=None)
    """
    The leaderboard start date in YYYY-MM-DD format. Defaults to today when omitted.
    """

    end: typing.Optional[str] = pydantic.Field(default=None)
    """
    The optional leaderboard end date in YYYY-MM-DD format.
    """

    breakdown_attributes: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="breakdownAttributes")
    ] = pydantic.Field(default=None)
    """
    The UUIDs of the active user attributes to break rankings down by.
    """

    run_unit: typing_extensions.Annotated[
        typing.Optional[CreateLeaderboardRequestItemRunUnit], FieldMetadata(alias="runUnit")
    ] = pydantic.Field(default=None)
    """
    How often the leaderboard repeats. Omit for a non-recurring leaderboard. Streak leaderboards cannot repeat.
    """

    run_interval: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="runInterval")] = (
        pydantic.Field(default=None)
    )
    """
    The number of `runUnit`s between repeats. Required when `runUnit` is set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
