# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CreatePointsTriggerRequestItemUserAttributesItem(UniversalBaseModel):
    attribute_id: typing_extensions.Annotated[str, FieldMetadata(alias="attributeId")] = pydantic.Field()
    """
    The UUID of the user attribute.
    """

    attribute_value: typing_extensions.Annotated[str, FieldMetadata(alias="attributeValue")] = pydantic.Field()
    """
    The value to match.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
