# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_attribute_request_item_type import CreateAttributeRequestItemType


class CreateAttributeRequestItem(UniversalBaseModel):
    """
    An attribute to create.
    """

    name: str = pydantic.Field()
    """
    The attribute name.
    """

    key: str = pydantic.Field()
    """
    The attribute key. Only alphanumeric characters, hyphens, and underscores are permitted.
    """

    type: CreateAttributeRequestItemType = pydantic.Field()
    """
    The attribute type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
