# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .created_points_boost_rounding import CreatedPointsBoostRounding
from .created_points_boost_status import CreatedPointsBoostStatus


class CreatedPointsBoost(UniversalBaseModel):
    """
    A successfully created points boost returned from the create endpoint.
    """

    id: str = pydantic.Field()
    """
    The UUID of the created boost.
    """

    name: str = pydantic.Field()
    """
    The name of the boost.
    """

    status: CreatedPointsBoostStatus = pydantic.Field()
    """
    The status of the boost.
    """

    start: str = pydantic.Field()
    """
    The start date (YYYY-MM-DD).
    """

    end: typing.Optional[str] = pydantic.Field(default=None)
    """
    The end date (YYYY-MM-DD) or null if no end date.
    """

    multiplier: float = pydantic.Field()
    """
    The points multiplier.
    """

    rounding: CreatedPointsBoostRounding = pydantic.Field()
    """
    How boosted points are rounded.
    """

    user_id: typing_extensions.Annotated[str, FieldMetadata(alias="userId")] = pydantic.Field()
    """
    The customer ID of the user the boost was created for.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
