# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .admin_issue import AdminIssue
from .deleted_resource import DeletedResource


class DeletePointsBoostsResponse(UniversalBaseModel):
    """
    Response containing the points boosts that were deleted and any per-item issues.
    """

    deleted: typing.List[DeletedResource] = pydantic.Field()
    """
    Array of deleted points boosts represented by ID.
    """

    issues: typing.List[AdminIssue] = pydantic.Field()
    """
    Array of issues encountered during boost archival.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
