# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .leaderboard_ranking import LeaderboardRanking
from .leaderboard_response import LeaderboardResponse
from .leaderboard_response_with_rankings_status import LeaderboardResponseWithRankingsStatus


class LeaderboardResponseWithRankings(LeaderboardResponse):
    status: LeaderboardResponseWithRankingsStatus = pydantic.Field()
    """
    The status of the leaderboard.
    """

    rankings: typing.List[LeaderboardRanking] = pydantic.Field()
    """
    Array of user rankings for the leaderboard.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
