# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class LeaderboardEvent(UniversalBaseModel):
    """
    A daily leaderboard snapshot entry representing the user's rank/value state and the previous persisted state.
    """

    date: str = pydantic.Field()
    """
    The leaderboard snapshot date in YYYY-MM-DD format.
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    Deprecated ISO timestamp for the snapshot day boundary. Use `date` instead.
    """

    previous_rank: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="previousRank"),
        pydantic.Field(
            alias="previousRank",
            description="The user's rank before this event, or null if they were not on the leaderboard.",
        ),
    ] = None
    rank: typing.Optional[int] = pydantic.Field(default=None)
    """
    The user's rank after this event, or null if they are no longer on the leaderboard.
    """

    previous_value: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="previousValue"),
        pydantic.Field(
            alias="previousValue",
            description="The user's value before this event, or null if they were not on the leaderboard.",
        ),
    ] = None
    value: typing.Optional[int] = pydantic.Field(default=None)
    """
    The user's value after this event, or null if they are no longer on the leaderboard.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
