# This file was auto-generated by Fern from our API Definition.

import typing

from .patch_points_boosts_request_item import PatchPointsBoostsRequestItem

PatchPointsBoostsRequest = typing.List[PatchPointsBoostsRequestItem]
