# This file was auto-generated by Fern from our API Definition.

import typing

from .points_level_summary_response_item import PointsLevelSummaryResponseItem

PointsLevelSummaryResponse = typing.List[PointsLevelSummaryResponseItem]
