# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .points_boost_webhook_payload_rounding import PointsBoostWebhookPayloadRounding
from .points_boost_webhook_payload_status import PointsBoostWebhookPayloadStatus


class PointsBoostWebhookPayload(UniversalBaseModel):
    """
    Points boost payload sent in points.boost_started and points.boost_finished webhook events.
    """

    id: str = pydantic.Field()
    """
    The ID of the points boost.
    """

    name: str = pydantic.Field()
    """
    The name of the points boost.
    """

    status: PointsBoostWebhookPayloadStatus = pydantic.Field()
    """
    The status of the points boost.
    """

    user_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="userId")] = pydantic.Field(
        default=None
    )
    """
    The customer-facing user ID that the boost is scoped to, or null for global boosts.
    """

    points_system_id: typing_extensions.Annotated[str, FieldMetadata(alias="pointsSystemId")] = pydantic.Field()
    """
    The ID of the points system this boost applies to.
    """

    points_system_key: typing_extensions.Annotated[str, FieldMetadata(alias="pointsSystemKey")] = pydantic.Field()
    """
    The key of the points system this boost applies to.
    """

    points_system_name: typing_extensions.Annotated[str, FieldMetadata(alias="pointsSystemName")] = pydantic.Field()
    """
    The name of the points system this boost applies to.
    """

    start: str = pydantic.Field()
    """
    The start date of the points boost (YYYY-MM-DD).
    """

    end: typing.Optional[str] = pydantic.Field(default=None)
    """
    The end date of the points boost (YYYY-MM-DD), or null if open-ended.
    """

    multiplier: float = pydantic.Field()
    """
    The multiplier applied to points during the boost.
    """

    rounding: PointsBoostWebhookPayloadRounding = pydantic.Field()
    """
    The rounding method applied to boosted points.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
