# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .points_boost_rounding import PointsBoostRounding
from .points_boost_status import PointsBoostStatus


class PointsBoost(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The ID of the points boost
    """

    name: str = pydantic.Field()
    """
    The name of the points boost
    """

    status: PointsBoostStatus = pydantic.Field()
    """
    The status of the points boost
    """

    start: str = pydantic.Field()
    """
    The start date of the points boost
    """

    end: typing.Optional[str] = pydantic.Field(default=None)
    """
    The end date of the points boost
    """

    multiplier: float = pydantic.Field()
    """
    The multiplier of the points boost
    """

    rounding: PointsBoostRounding = pydantic.Field()
    """
    The rounding method of the points boost
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
