# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PointsLevel(UniversalBaseModel):
    """
    A level within a points system.
    """

    id: str = pydantic.Field()
    """
    The ID of the level
    """

    key: str = pydantic.Field()
    """
    The unique key of the level
    """

    name: str = pydantic.Field()
    """
    The name of the level
    """

    description: str = pydantic.Field()
    """
    The description of the level
    """

    badge_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="badgeUrl")] = pydantic.Field(
        default=None
    )
    """
    The URL of the badge image for the level
    """

    points: int = pydantic.Field()
    """
    The points threshold required to reach this level
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
