# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bulk_insert_issue import BulkInsertIssue


class RestoreStreaksResponse(UniversalBaseModel):
    """
    Response containing restored users and any issues encountered.
    """

    restored_users: typing_extensions.Annotated[typing.List[str], FieldMetadata(alias="restoredUsers")] = (
        pydantic.Field()
    )
    """
    Array of user IDs whose streaks were successfully restored.
    """

    issues: typing.List[BulkInsertIssue] = pydantic.Field()
    """
    Array of issues encountered during streak restoration.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
