# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class StreakMetricPreference(UniversalBaseModel):
    """
    Per-metric streak threshold override for a user.
    """

    key: str = pydantic.Field()
    """
    The metric key.
    """

    threshold: float = pydantic.Field()
    """
    Minimum metric change in a streak period to count toward the streak.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
