# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class StreakResponsePausesItem(UniversalBaseModel):
    """
    An object representing a streak pause.
    """

    id: str = pydantic.Field()
    """
    The unique ID of the streak pause.
    """

    start: str = pydantic.Field()
    """
    The first date the pause covers.
    """

    end: str = pydantic.Field()
    """
    The last date the pause covers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
