# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from .base_streak_response import BaseStreakResponse
from .streak_response_streak_history_item import StreakResponseStreakHistoryItem


class StreakResponse(BaseStreakResponse):
    """
    An object representing the user's streak.
    """

    extended: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    The timestamp the streak was most recently extended. Null if the streak is not active.
    """

    streak_history: typing_extensions.Annotated[
        typing.List[StreakResponseStreakHistoryItem], FieldMetadata(alias="streakHistory")
    ] = pydantic.Field()
    """
    A list of the user's past streak periods up through the current period. Each period includes the start and end dates and the length of the streak.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
