# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UpdateAttributeRequestItem(UniversalBaseModel):
    """
    An attribute update object. `id` is required and `name` is optional. `key` and `type` cannot be changed through this endpoint.
    """

    id: str = pydantic.Field()
    """
    The UUID of the attribute to update.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The updated attribute name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
