# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class UpdateStreakSettingsFreezes(UniversalBaseModel):
    """
    Replacement freeze configuration. `startCount` and `maxCount` are required. Auto-earn is a pair: both `autoEarnInterval` and `autoEarnAmount` must be set to enable auto-earn, or both omitted/`null` to disable it.
    """

    start_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="startCount"),
        pydantic.Field(alias="startCount", description="Number of freezes new users start with."),
    ]
    max_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="maxCount"),
        pydantic.Field(
            alias="maxCount",
            description="Maximum number of freezes a user can have. Must be greater than or equal to `startCount`.",
        ),
    ]
    auto_earn_interval: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="autoEarnInterval"),
        pydantic.Field(alias="autoEarnInterval", description="Days between auto-earned freezes."),
    ] = None
    auto_earn_amount: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="autoEarnAmount"),
        pydantic.Field(alias="autoEarnAmount", description="Freezes earned per interval."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
