# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .admin_font_family import AdminFontFamily
from .update_admin_settings_branding_app_icon import UpdateAdminSettingsBrandingAppIcon
from .update_admin_settings_branding_logo import UpdateAdminSettingsBrandingLogo


class UpdateAdminSettingsBranding(UniversalBaseModel):
    """
    Branding fields to update. Omitted fields stay as-is.
    """

    app_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="appName"),
        pydantic.Field(alias="appName", description="The name of the app or platform."),
    ] = None
    app_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="appUrl"),
        pydantic.Field(alias="appUrl", description="The URL of the app or platform."),
    ] = None
    brand_color: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="brandColor"),
        pydantic.Field(
            alias="brandColor",
            description="Primary brand color as hex (`#RGB` or `#RRGGBB`), `rgb(r,g,b)`, or `rgba(r,g,b,a)`.",
        ),
    ] = None
    font: typing.Optional[AdminFontFamily] = None
    logo: typing.Optional[UpdateAdminSettingsBrandingLogo] = pydantic.Field(default=None)
    """
    Company logo, or `null` to clear it.
    """

    app_icon: typing_extensions.Annotated[
        typing.Optional[UpdateAdminSettingsBrandingAppIcon],
        FieldMetadata(alias="appIcon"),
        pydantic.Field(alias="appIcon", description="App icon, or `null` to clear it."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
