# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .admin_issue import AdminIssue
from .created_metric import CreatedMetric


class UpdateMetricsResponse(UniversalBaseModel):
    """
    Response containing updated metrics and any per-item issues identified by metric ID.
    """

    updated: typing.List[CreatedMetric] = pydantic.Field()
    """
    Array of successfully updated metrics.
    """

    issues: typing.List[AdminIssue] = pydantic.Field()
    """
    Array of issues encountered during metric update.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
