# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .update_points_system_request_item_badge import UpdatePointsSystemRequestItemBadge


class UpdatePointsSystemRequestItem(UniversalBaseModel):
    """
    A points system update object. Only id is required; all other fields are optional.
    """

    id: str = pydantic.Field()
    """
    The UUID of the points system to update.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Updated name.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Updated description.
    """

    badge: typing.Optional[UpdatePointsSystemRequestItemBadge] = pydantic.Field(default=None)
    """
    Updated badge. Set to null to remove.
    """

    max_points: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="maxPoints")] = pydantic.Field(
        default=None
    )
    """
    Updated max points. Set to null to remove.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
