# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .points_boost_webhook_payload import PointsBoostWebhookPayload


class WebhooksPointsBoostStartedPayload(UniversalBaseModel):
    type: typing.Literal["points.boost_started"] = pydantic.Field(default="points.boost_started")
    """
    The webhook event type.
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    When the event occurred (ISO 8601).
    """

    boost: PointsBoostWebhookPayload = pydantic.Field()
    """
    The points boost that started.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
