# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .points_level import PointsLevel
from .user import User
from .webhooks_points_level_changed_payload_points import WebhooksPointsLevelChangedPayloadPoints


class WebhooksPointsLevelChangedPayload(UniversalBaseModel):
    type: typing.Literal["points.level_changed"] = pydantic.Field(default="points.level_changed")
    """
    The webhook event type.
    """

    user: User = pydantic.Field()
    """
    The user whose level changed.
    """

    points: WebhooksPointsLevelChangedPayloadPoints = pydantic.Field()
    """
    The points system in which the level changed.
    """

    previous_level: typing_extensions.Annotated[typing.Optional[PointsLevel], FieldMetadata(alias="previousLevel")] = (
        pydantic.Field(default=None)
    )
    """
    The user's previous level, or null if the user had no level.
    """

    new_level: typing_extensions.Annotated[typing.Optional[PointsLevel], FieldMetadata(alias="newLevel")] = (
        pydantic.Field(default=None)
    )
    """
    The user's new level, or null if the user no longer has a level.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
