# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user import User


class WebhooksStreakFreezeEarnedPayload(UniversalBaseModel):
    type: typing.Literal["streak.freeze_earned"] = pydantic.Field(default="streak.freeze_earned")
    """
    The webhook event type.
    """

    user: User = pydantic.Field()
    """
    The user who earned streak freezes.
    """

    earned: int = pydantic.Field()
    """
    The number of freezes earned.
    """

    freezes: int = pydantic.Field()
    """
    The total number of freezes the user has after the event.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
