# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WebhooksEmailsReactivationDuePayloadReactivation(UniversalBaseModel):
    """
    Details about the reactivation message.
    """

    message_number: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="messageNumber"),
        pydantic.Field(alias="messageNumber", description="The reactivation message number in the sequence."),
    ]
    days_since_last_active: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="daysSinceLastActive"),
        pydantic.Field(alias="daysSinceLastActive", description="The number of days since the user was last active."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
