# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user import User
from .webhooks_emails_recap_due_payload_recap import WebhooksEmailsRecapDuePayloadRecap


class WebhooksEmailsRecapDuePayload(UniversalBaseModel):
    type: typing.Literal["emails.recap_due"] = pydantic.Field(default="emails.recap_due")
    """
    The webhook event type.
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    The time the webhook was sent.
    """

    user: User = pydantic.Field()
    """
    The user the recap is due for.
    """

    recap: WebhooksEmailsRecapDuePayloadRecap = pydantic.Field()
    """
    Details about the recap period.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
