# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .wrapped_activity_period import WrappedActivityPeriod


class WrappedMostActiveWeek(WrappedActivityPeriod):
    """
    The user's most active week during the year.
    """

    start: str = pydantic.Field()
    """
    The start date of the most active week in YYYY-MM-DD format.
    """

    end: str = pydantic.Field()
    """
    The end date of the most active week in YYYY-MM-DD format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
