# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .wrapped_metric_by_attribute_value_value import WrappedMetricByAttributeValueValue


class WrappedMetric(UniversalBaseModel):
    """
    A user's metric data for a wrapped period.
    """

    name: str = pydantic.Field()
    """
    The name of the metric.
    """

    units: typing.Optional[str] = pydantic.Field(default=None)
    """
    The units of the metric.
    """

    current_total: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="currentTotal"),
        pydantic.Field(alias="currentTotal", description="The user's current total for the metric."),
    ]
    change_this_period: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="changeThisPeriod"),
        pydantic.Field(alias="changeThisPeriod", description="The change in the metric value during the period."),
    ]
    percent_change: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="percentChange"),
        pydantic.Field(
            alias="percentChange", description="The percentage change in the metric value during the period."
        ),
    ]
    percentile_this_period: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="percentileThisPeriod"),
        pydantic.Field(
            alias="percentileThisPeriod",
            description="The user's percentile rank for this metric during the period. Only included for weekly, monthly, and yearly aggregation periods.",
        ),
    ] = None
    by_attribute: typing_extensions.Annotated[
        typing.Dict[str, typing.Dict[str, WrappedMetricByAttributeValueValue]],
        FieldMetadata(alias="byAttribute"),
        pydantic.Field(alias="byAttribute", description="Metric data broken down by attribute key and value."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
