# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from .wrapped_activity_period import WrappedActivityPeriod
from .wrapped_streak import WrappedStreak


class WrappedEntireYear(WrappedActivityPeriod):
    """
    The user's activity data for the entire year.
    """

    longest_streak: typing_extensions.Annotated[WrappedStreak, FieldMetadata(alias="longestStreak")] = pydantic.Field()
    """
    The user's longest streak during the year.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
