# This file was auto-generated by Fern from our API Definition.

import typing

UsersPointsEventSummaryRequestAggregation = typing.Union[
    typing.Literal["daily", "weekly", "monthly"], typing.Any
]
