# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.admin_attribute import AdminAttribute
from ...types.create_attributes_request import CreateAttributesRequest
from ...types.create_attributes_response import CreateAttributesResponse
from ...types.delete_attributes_response import DeleteAttributesResponse
from ...types.list_attributes_response import ListAttributesResponse
from ...types.update_attributes_request import UpdateAttributesRequest
from ...types.update_attributes_response import UpdateAttributesResponse
from .raw_client import AsyncRawAttributesClient, RawAttributesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AttributesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAttributesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAttributesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAttributesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAttributesResponse:
        """
        List attributes.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of records to return.

        skip : typing.Optional[int]
            Number of records to skip from the start of the list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAttributesResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.attributes.list(
            limit=1,
            skip=1,
        )
        """
        _response = self._raw_client.list(limit=limit, skip=skip, request_options=request_options)
        return _response.data

    def create(
        self, *, request: CreateAttributesRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAttributesResponse:
        """
        Create attributes in bulk.

        Parameters
        ----------
        request : CreateAttributesRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAttributesResponse
            Successful operation (no attributes created)

        Examples
        --------
        from trophy import CreateAttributeRequestItem, TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.attributes.create(
            request=[
                CreateAttributeRequestItem(
                    name="Plan",
                    key="plan",
                    type="user",
                ),
                CreateAttributeRequestItem(
                    name="Device",
                    key="device",
                    type="event",
                ),
            ],
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    def delete(
        self,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteAttributesResponse:
        """
        Delete attributes in bulk by ID.

        Parameters
        ----------
        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Attribute IDs to delete. Repeat the query param or provide a comma-separated list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAttributesResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.attributes.delete()
        """
        _response = self._raw_client.delete(ids=ids, request_options=request_options)
        return _response.data

    def update(
        self, *, request: UpdateAttributesRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateAttributesResponse:
        """
        Update attributes in bulk by ID.

        Parameters
        ----------
        request : UpdateAttributesRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAttributesResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi, UpdateAttributeRequestItem

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.attributes.update(
            request=[
                UpdateAttributeRequestItem(
                    id="550e8400-e29b-41d4-a716-446655440000",
                    name="Subscription Plan",
                )
            ],
        )
        """
        _response = self._raw_client.update(request=request, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AdminAttribute:
        """
        Get an attribute by ID.

        Parameters
        ----------
        id : str
            The UUID of the attribute to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminAttribute
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.attributes.get(
            id="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data


class AsyncAttributesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAttributesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAttributesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAttributesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAttributesResponse:
        """
        List attributes.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of records to return.

        skip : typing.Optional[int]
            Number of records to skip from the start of the list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAttributesResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.attributes.list(
                limit=1,
                skip=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(limit=limit, skip=skip, request_options=request_options)
        return _response.data

    async def create(
        self, *, request: CreateAttributesRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAttributesResponse:
        """
        Create attributes in bulk.

        Parameters
        ----------
        request : CreateAttributesRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAttributesResponse
            Successful operation (no attributes created)

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, CreateAttributeRequestItem

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.attributes.create(
                request=[
                    CreateAttributeRequestItem(
                        name="Plan",
                        key="plan",
                        type="user",
                    ),
                    CreateAttributeRequestItem(
                        name="Device",
                        key="device",
                        type="event",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    async def delete(
        self,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteAttributesResponse:
        """
        Delete attributes in bulk by ID.

        Parameters
        ----------
        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Attribute IDs to delete. Repeat the query param or provide a comma-separated list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAttributesResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.attributes.delete()


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(ids=ids, request_options=request_options)
        return _response.data

    async def update(
        self, *, request: UpdateAttributesRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateAttributesResponse:
        """
        Update attributes in bulk by ID.

        Parameters
        ----------
        request : UpdateAttributesRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAttributesResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, UpdateAttributeRequestItem

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.attributes.update(
                request=[
                    UpdateAttributeRequestItem(
                        id="550e8400-e29b-41d4-a716-446655440000",
                        name="Subscription Plan",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(request=request, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AdminAttribute:
        """
        Get an attribute by ID.

        Parameters
        ----------
        id : str
            The UUID of the attribute to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminAttribute
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.attributes.get(
                id="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data
