# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.restore_streaks_response import RestoreStreaksResponse
from .raw_client import AsyncRawStreaksClient, RawStreaksClient
from .types.restore_streaks_request_users_item import RestoreStreaksRequestUsersItem

if typing.TYPE_CHECKING:
    from .freezes.client import AsyncFreezesClient, FreezesClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StreaksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStreaksClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._freezes: typing.Optional[FreezesClient] = None

    @property
    def with_raw_response(self) -> RawStreaksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStreaksClient
        """
        return self._raw_client

    def restore(
        self,
        *,
        users: typing.Sequence[RestoreStreaksRequestUsersItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RestoreStreaksResponse:
        """
        Restore streaks for multiple users to the maximum length in the last 90 days (in the case of daily streaks), one year (in the case of weekly streaks), or two years (in the case of monthly streaks).

        Parameters
        ----------
        users : typing.Sequence[RestoreStreaksRequestUsersItem]
            Array of users to restore streaks for. Maximum 100 users per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RestoreStreaksResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi
        from trophy.admin.streaks import RestoreStreaksRequestUsersItem

        client = TrophyApi(
            api_key="YOUR_API_KEY",
        )
        client.admin.streaks.restore(
            users=[
                RestoreStreaksRequestUsersItem(
                    id="user-123",
                ),
                RestoreStreaksRequestUsersItem(
                    id="user-456",
                ),
            ],
        )
        """
        _response = self._raw_client.restore(users=users, request_options=request_options)
        return _response.data

    @property
    def freezes(self):
        if self._freezes is None:
            from .freezes.client import FreezesClient  # noqa: E402

            self._freezes = FreezesClient(client_wrapper=self._client_wrapper)
        return self._freezes


class AsyncStreaksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStreaksClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._freezes: typing.Optional[AsyncFreezesClient] = None

    @property
    def with_raw_response(self) -> AsyncRawStreaksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStreaksClient
        """
        return self._raw_client

    async def restore(
        self,
        *,
        users: typing.Sequence[RestoreStreaksRequestUsersItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RestoreStreaksResponse:
        """
        Restore streaks for multiple users to the maximum length in the last 90 days (in the case of daily streaks), one year (in the case of weekly streaks), or two years (in the case of monthly streaks).

        Parameters
        ----------
        users : typing.Sequence[RestoreStreaksRequestUsersItem]
            Array of users to restore streaks for. Maximum 100 users per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RestoreStreaksResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi
        from trophy.admin.streaks import RestoreStreaksRequestUsersItem

        client = AsyncTrophyApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.streaks.restore(
                users=[
                    RestoreStreaksRequestUsersItem(
                        id="user-123",
                    ),
                    RestoreStreaksRequestUsersItem(
                        id="user-456",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.restore(users=users, request_options=request_options)
        return _response.data

    @property
    def freezes(self):
        if self._freezes is None:
            from .freezes.client import AsyncFreezesClient  # noqa: E402

            self._freezes = AsyncFreezesClient(client_wrapper=self._client_wrapper)
        return self._freezes
