# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...types.leaderboard_response import LeaderboardResponse
from .leaderboards_all_response_item_status import LeaderboardsAllResponseItemStatus


class LeaderboardsAllResponseItem(LeaderboardResponse):
    status: LeaderboardsAllResponseItemStatus = pydantic.Field()
    """
    The status of the leaderboard.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
