# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations


class TrophyApiEnvironment:
    PRODUCTION: TrophyApiEnvironment

    def __init__(self, *, api: str, admin: str):
        self.api = api
        self.admin = admin


TrophyApiEnvironment.PRODUCTION = TrophyApiEnvironment(
    api="https://api.trophy.so/v1", admin="https://admin.trophy.so/v1"
)
