# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.admin_tenant import AdminTenant
from ...types.create_tenants_request import CreateTenantsRequest
from ...types.create_tenants_response import CreateTenantsResponse
from ...types.delete_tenants_response import DeleteTenantsResponse
from ...types.list_tenants_response import ListTenantsResponse
from ...types.update_tenants_request import UpdateTenantsRequest
from ...types.update_tenants_response import UpdateTenantsResponse
from .raw_client import AsyncRawTenantsClient, RawTenantsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TenantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTenantsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTenantsResponse:
        """
        List tenants in the current environment.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of records to return.

        skip : typing.Optional[int]
            Number of records to skip from the start of the list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTenantsResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.tenants.list(
            limit=1,
            skip=1,
        )
        """
        _response = self._raw_client.list(limit=limit, skip=skip, request_options=request_options)
        return _response.data

    def create(
        self, *, request: CreateTenantsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateTenantsResponse:
        """
        Create tenants.

        Parameters
        ----------
        request : CreateTenantsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTenantsResponse
            Successful operation (no tenants created)

        Examples
        --------
        from trophy import CreateTenantRequestItem, TrophyApi

        client = TrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.tenants.create(
            request=[
                CreateTenantRequestItem(
                    customer_id="customer_12345",
                    name="Acme Corp",
                ),
                CreateTenantRequestItem(
                    customer_id="customer_67890",
                    name="Globex Inc",
                ),
            ],
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    def delete(
        self,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteTenantsResponse:
        """
        Delete tenants by ID.

        Parameters
        ----------
        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Tenant IDs to delete. Repeat the query param or provide a comma-separated list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteTenantsResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.tenants.delete(
            ids=[
                "550e8400-e29b-41d4-a716-446655440000",
                "550e8400-e29b-41d4-a716-446655440001",
            ],
        )
        """
        _response = self._raw_client.delete(ids=ids, request_options=request_options)
        return _response.data

    def update(
        self, *, request: UpdateTenantsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateTenantsResponse:
        """
        Update tenants by ID.

        Parameters
        ----------
        request : UpdateTenantsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTenantsResponse
            Successful operation

        Examples
        --------
        from trophy import TrophyApi, UpdateTenantRequestItem

        client = TrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.tenants.update(
            request=[
                UpdateTenantRequestItem(
                    id="550e8400-e29b-41d4-a716-446655440000",
                    name="Acme Corporation",
                )
            ],
        )
        """
        _response = self._raw_client.update(request=request, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AdminTenant:
        """
        Get a tenant by ID.

        Parameters
        ----------
        id : str
            The UUID of the tenant to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminTenant
            Successful operation

        Examples
        --------
        from trophy import TrophyApi

        client = TrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )
        client.admin.tenants.get(
            id="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data


class AsyncTenantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTenantsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        skip: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTenantsResponse:
        """
        List tenants in the current environment.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of records to return.

        skip : typing.Optional[int]
            Number of records to skip from the start of the list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTenantsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.tenants.list(
                limit=1,
                skip=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(limit=limit, skip=skip, request_options=request_options)
        return _response.data

    async def create(
        self, *, request: CreateTenantsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateTenantsResponse:
        """
        Create tenants.

        Parameters
        ----------
        request : CreateTenantsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTenantsResponse
            Successful operation (no tenants created)

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, CreateTenantRequestItem

        client = AsyncTrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.tenants.create(
                request=[
                    CreateTenantRequestItem(
                        customer_id="customer_12345",
                        name="Acme Corp",
                    ),
                    CreateTenantRequestItem(
                        customer_id="customer_67890",
                        name="Globex Inc",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    async def delete(
        self,
        *,
        ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteTenantsResponse:
        """
        Delete tenants by ID.

        Parameters
        ----------
        ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Tenant IDs to delete. Repeat the query param or provide a comma-separated list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteTenantsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.tenants.delete(
                ids=[
                    "550e8400-e29b-41d4-a716-446655440000",
                    "550e8400-e29b-41d4-a716-446655440001",
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(ids=ids, request_options=request_options)
        return _response.data

    async def update(
        self, *, request: UpdateTenantsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateTenantsResponse:
        """
        Update tenants by ID.

        Parameters
        ----------
        request : UpdateTenantsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTenantsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi, UpdateTenantRequestItem

        client = AsyncTrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.tenants.update(
                request=[
                    UpdateTenantRequestItem(
                        id="550e8400-e29b-41d4-a716-446655440000",
                        name="Acme Corporation",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(request=request, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AdminTenant:
        """
        Get a tenant by ID.

        Parameters
        ----------
        id : str
            The UUID of the tenant to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AdminTenant
            Successful operation

        Examples
        --------
        import asyncio

        from trophy import AsyncTrophyApi

        client = AsyncTrophyApi(
            "1.18.0",
            tenant_id="YOUR_TENANT_ID",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin.tenants.get(
                id="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data
